# Generated by Django 3.2.3 on 2021-07-13 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
